version: '3.1'

services:
     app:
       build: ./
       ports:
           - '8080:8080'
       restart: always
       links:
           - mysql_db

     mysql_db:
       image: mysql:5.6
       ports:
           - '3306:3306'
       volumes:
           - './data:/var/lib/mysql'
       restart: always
       environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: mydb


